version: "3"
services:
  plausible_db:
    image: postgres:16-alpine
    restart: always
    networks:
      - dokploy-network
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    networks:
      - dokploy-network
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ../files/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ../files/clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    env_file:
      - .env
    ports:
      - 8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.sass-plausible-c80e44-105-web.rule=Host(`s.mytreasurepocket.com`)
      - traefik.http.routers.sass-plausible-c80e44-105-web.entrypoints=web
      - traefik.http.services.sass-plausible-c80e44-105-web.loadbalancer.server.port=8000
      - traefik.http.routers.sass-plausible-c80e44-105-web.service=sass-plausible-c80e44-105-web
      - traefik.http.routers.sass-plausible-c80e44-105-web.middlewares=redirect-to-https@file
      - traefik.http.routers.sass-plausible-c80e44-105-websecure.rule=Host(`s.mytreasurepocket.com`)
      - traefik.http.routers.sass-plausible-c80e44-105-websecure.entrypoints=websecure
      - traefik.http.services.sass-plausible-c80e44-105-websecure.loadbalancer.server.port=8000
      - traefik.http.routers.sass-plausible-c80e44-105-websecure.service=sass-plausible-c80e44-105-websecure
      - traefik.http.routers.sass-plausible-c80e44-105-websecure.tls.certresolver=letsencrypt
    networks:
      - dokploy-network
volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  event-logs:
    driver: local
networks:
  dokploy-network:
    external: true
